name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Cache SonarQube packages
        uses: actions/cache@v2
        with:
          path: ～/.sonar/cache
          key: $ {{ runner.os }}-sonar- $ {{ hashFiles('package-lock.json') }}
          restore-keys: |
            $ {{ runner.os }}-sonar-

      - name: Install SonarScanner
        run: choco install sonar-scanner-cli --version=4.6.2.2472 -y

      - name: Run SonarQube analysis
        env:
          SONAR_HOST_URL: $ {{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: $ {{ secrets.SONAR_TOKEN }}
        run: >
          sonar-scanner.bat
          -Dsonar.projectKey=<sonarTest1>
          -Dsonar.sources=.
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
